server:
  port: 9010
spring:
  application:
    name: account
  datasource:
    url: jdbc:mysql://ec2-54-82-174-195.compute-1.amazonaws.com:3306/deploy?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ahmet
    hikari:
      connection-timeout: 3000000
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  cloud:
    discovery:
      enabled: true
